name: Deploy to GitHub Pages Repo

on:
  push:
    branches: [main, master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies & generate localization
        run: |
          flutter pub get
          flutter gen-l10n

      - name: Build Web Application
        run: flutter build web --release --base-href "/"

      - name: Deploy to External Repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.TARGET_REPO_TOKEN }}
          external_repository: kharoldcanova/kharoldcanova.github.io
          publish_dir: ./build/web
          publish_branch: main